services:
  - type: web
    name: inventrack-api
    runtime: docker
    region: frankfurt
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    autoDeployTrigger: commit
    envVars:
      - key: ENVIRONMENT
        value: production
